## this parameter file is used to configure the surf extraction module
/**:
  ros__parameters:
    preprocessing:
      extraction:
        # [ conversion_extraction, feature_extraction ]
        type: "conversion_extraction"

        # specify which conversions to do between different image formats from:
        # RGB_TO_GRAYSCALE, RGB_TO_COLOR_CONSTANT
        conversions: ["RGB_TO_GRAYSCALE", "RGB_TO_COLOR_CONSTANT"]

        # color constant settings
        color_constant:
          weights: [0.43]
          histogram_equalization: false

        extractor:
          # we're providing the surf settings (don't change this param, use a different file)
          type: "ASRL_GPU_SURF"
          surf:
            upright_flag: true
            threshold: .000001
            nOctaves: 4
            nIntervals: 4
            initialScale: 1.5
            edgeScale: 1.5
            l1: 2.0 # 3.f/1.5f
            l2: 3.333333 # 5.f/1.5f
            l3: 2.0 # 3.f/1.5f
            l4: 0.666667 # 1.f/1.5f
            initialStep: 1
            targetFeatures: 600
            detector_threads_x: 16
            detector_threads_y: 16
            regions_horizontal: 16
            regions_vertical: 16
            regions_target: 600
            stereoDisparityMinimum: 0.0
            stereoDisparityMaximum: 64
            stereoCorrelationThreshold: .79
            stereoYTolerance: 0.5
            stereoScaleTolerance: .9
