## this parameter file is used to configure the ORB extraction module
/**:
  ros__parameters:
    preprocessing:
      extraction:
        # [ conversion_extraction, feature_extraction ]
        type: "conversion_extraction"

        # specify which conversions to do between different image formats from:
        # RGB_TO_GRAYSCALE, RGB_TO_COLOR_CONSTANT
        conversions: ["RGB_TO_GRAYSCALE"]

        # color constant settings
        color_constant: { weights: [0.43], histogram_equalization: false }

        extractor: {
            # we're providing the surf settings (don't change this param, use a different file)
            type: "OPENCV_ORB",
            channels: ["grayscale"],
            orb: {
                upright_flag: false,
                use_STAR_detector: true, # false == FAST detector
                use_GPU_descriptors: false,
                STAR_maxSize: 5,
                STAR_responseThreshold: 10,
                STAR_lineThresholdProjected: 10,
                STAR_lineThresholdBinarized: 8,
                STAR_suppressNonmaxSize: 5,
                num_detector_features: 15000,
                num_binned_features: 2000,
                scaleFactor: 2.0,
                nlevels: 4,
                edgeThreshold: 8,
                firstLevel: 0,
                WTA_K: 2,
                scoreType: HARRIS,
                patchSize: 64,
                fastThreshold: 20,
                x_bins: 6,
                y_bins: 4,

                matcher:
                  {
                    descriptor_match_thresh: 0.55,
                    stereo_descriptor_match_thresh: 0.55,
                    stereo_y_tolerance: 2.0,
                    stereo_x_tolerance_min: 0.0,
                    stereo_x_tolerance_max: 250.0,
                    check_octave: true,
                    check_response: true,
                    min_response_ratio: 0.2,
                    scale_x_tolerance_by_y: true,
                    x_tolerance_scale: 768,
                  },
              },
          }
