/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: false

    # The lidar frame from the urdf (also defines the rig name)
    lidar_frame: velodyne
    # The control frame from the urdf
    control_frame: base_link

    ############ tactic configuration ############
    tactic:
      visualize: true
      extrapolate_odometry: true # path tracker
      default_loc_cov: [1.0, 0.5, 0.5, 0.25, 0.25, 0.5]
      merge_threshold: [5.0, 3.0, 0.2]
      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 3.0
      live_mem:
        enable: true
        lookahead_distance: 100
        window_size: 10
      map_mem:
        enable: true
        lookahead_distance: 15
        vertex_life_span: 10

    ############ pipeline configuration ############
    pipeline:
      type: lidar
      # modules
      preprocessing: ["preprocessing"]
      odometry: ["recall", "icp", "keyframe_test", "mapping"]
      localization: ["recall", "icp"]
      # pipeline parameters
      map_voxel_size: 0.2

    preprocessing:
      preprocessing:
        type: "lidar.preprocessing"
        num_threads: 8
        num_channels: 64
        vertical_angle_res: 0.00745
        polar_r_scale: 1.5
        r_scale: 2.0
        h_scale: 0.5
        num_sample1: 90000
        num_sample2: 90000
        min_norm_score1: 0.0
        min_norm_score2: 0.01
        frame_voxel_size: 0.3
        visualize: true

    odometry:
      recall:
        type: "lidar.map_recall"
        map_voxel_size: 0.2
        visualize: true

      icp:
        type: "lidar.icp"
        source: "live"

        use_pose_prior: false
        trajectory_smoothing: true
        use_constant_acc: false
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.01
        lin_acc_std_dev_z: 0.01
        ang_acc_std_dev_x: 0.01
        ang_acc_std_dev_y: 0.01
        ang_acc_std_dev_z: 1.0

        num_threads: 8
        n_samples: 1000
        max_pairing_dist: 2.0
        max_planar_dist: 0.3
        avg_steps: 5
        max_iter: 100

        min_matched_ratio: 0.4

      mapping:
        type: "lidar.map_maintenance"
        map_voxel_size: 0.2
        # dynamic objects removal
        horizontal_resolution: 0.01
        vertical_resolution: 0.01
        visualize: true

      keyframe_test:
        type: "lidar.keyframe_test"
        min_translation: 4.0
        min_rotation: 30.0
        min_matched_points_ratio: 0.5

    localization:
      recall:
        type: "lidar.windowed_map_recall"
        map_voxel_size: 0.2
        depth: 1
        visualize: true

      icp:
        type: "lidar.icp"
        source: "map"
        use_pose_prior: true
        trajectory_smoothing: false
        min_matched_ratio: 0.4
        num_threads: 8
        n_samples: 1000
        max_pairing_dist: 2.0
        max_planar_dist: 0.3
        avg_steps: 5
        max_iter: 100
        verbose: true
