/**:
  ros__parameters:
    ############ system configuration ############
    # Data logging
    log_to_file: true
    log_debug: false
    log_enabled:
      [
        "navigator",
        "map_projector",
        "tactic",
        "tactic.module",
        "mission_planning_server",
        "state_machine",
        "pose_graph",
        "lidar.pipeline",
        "lidar.velodyne_converter",
        "lidar.honeycomb_converter",
        "lidar.preprocessing",
        "lidar.odometry_icp",
        "lidar.map_maintenance",
        "lidar.keyframe_test",
        "lidar.windowed_map_recall",
        "lidar.localization_icp",
        "path_tracker",
      ]

    # The lidar frame from the urdf (also defines the rig name)
    lidar_frame: velodyne
    # The control frame from the urdf
    robot_frame: base_link
    #
    camera_topic: not_used

    ############ map projection configuration ############
    map_projection:
      origin_lat: 43.78220
      origin_lng: -79.4661
      origin_theta: 1.3 # positive == clockwise
      scale: 1.0

    ############ tactic configuration ############
    tactic:
      extrapolate_odometry: true # path tracker
      localization_only_keyframe: false
      localization_skippable: true
      default_loc_cov: [1.0, 0.5, 0.5, 0.25, 0.25, 0.5]
      merge_threshold: [5.0, 3.0, 0.2]
      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 5
        search_back_depth: 10
        distance_warning: 3.0
      live_mem:
        enable: true
        lookahead_distance: 100
        window_size: 10
      map_mem:
        enable: true
        lookahead_distance: 15
        vertex_life_span: 10

      visualize: true
      vis_loc_path_offset: [0., 0., 0.]

    ############ pipeline configuration ############
    pipeline:
      type: lidar
      # modules
      preprocessing: ["conversion", "filtering"]
      odometry: ["recall", "icp", "mapping", "keyframe_test"]
      localization: ["recall", "icp"]
      # pipeline parameters
      map_voxel_size: 0.2

    preprocessing:
      conversion:
        type: "lidar.velodyne_converter"
        visualize: true

      filtering:
        type: "lidar.preprocessing"
        num_threads: 8

        frame_voxel_size: 0.3

        vertical_angle_res: 0.00745
        polar_r_scale: 1.5
        r_scale: 2.0
        h_scale: 0.5
        num_sample1: 90000
        min_norm_score1: 0.0

        num_sample2: 90000
        min_norm_score2: 0.01
        min_normal_estimate_dist: 5.0
        max_normal_estimate_angle: 0.417

        cluster_num_sample: 10000

        visualize: true

    odometry:
      recall:
        type: "lidar.map_recall"
        map_voxel_size: 0.2
        visualize: true

      icp:
        type: "lidar.odometry_icp"

        # Prior terms
        trajectory_smoothing: true
        use_constant_acc: false
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.01
        lin_acc_std_dev_z: 0.01
        ang_acc_std_dev_x: 0.01
        ang_acc_std_dev_y: 0.01
        ang_acc_std_dev_z: 1.0

        # ICP parameters
        num_threads: 12
        first_num_steps: 3
        initial_max_iter: 100
        initial_num_samples: 1000
        initial_max_pairing_dist: 2.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 5000
        refined_max_pairing_dist: 2.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.4

      mapping:
        type: "lidar.map_maintenance"
        map_voxel_size: 0.2

        # dynamic objects removal
        horizontal_resolution: 0.01
        vertical_resolution: 0.01
        min_num_observations: 0
        max_num_observations: 20

        visualize: true

      keyframe_test:
        type: "lidar.keyframe_test"

        min_translation: 0.0
        min_rotation: 0.0
        max_translation: 4.0
        max_rotation: 30.0

        min_matched_points_ratio: 0.4

        max_num_points: 100000

    localization:
      recall:
        type: "lidar.windowed_map_recall"
        single_exp_map_voxel_size: 0.2
        multi_exp_map_voxel_size: 0.2

        remove_short_term_dynamic: false
        short_term_min_num_observations: 1
        short_term_min_movability: 0.5

        depth: 1
        num_additional_exps: 0
        long_term_min_num_observations: 1

        visualize: true

      icp:
        type: "lidar.localization_icp"

        use_pose_prior: true

        # ICP parameters
        num_threads: 12
        first_num_steps: 3
        initial_max_iter: 100
        initial_num_samples: 1000
        initial_max_pairing_dist: 2.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 5000
        refined_max_pairing_dist: 2.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.4
