# This file contains params that are specific to this robot for this module. These params override the base params and are themselves overriden by the scenario params
navigator:
  ros__parameters:
    tactic:
      robot_index: 666
      loc_deadreckoning_thresh: [0.5, 0.1, 0.1]
      loc_lost_thresh: [1.0, 0.5, 0.25]
      extrapolate_VO: true
      extrapolate_timeout: 1.5

    stream_name: "/front_xb3/images"

    # drop images from the navigator queue if there is already one in the queue
    drop_frames: true

    # memory managers
    map_memory:
      enable: true
      streams_to_load:
        - "/front_xb3/landmarks"
        - "/front_xb3/landmarks/counts"
        - "/front_xb3/landmarks/matches"
        - "/control/experience"
      priv_streams_to_load:
        - "/front_xb3/visualization_images"
    live_memory:
      enable: true

    mergepipeline:
      default_loc_cov: [1.0, 0.5, 0.5, 0.25, 0.25, 0.5]
