## This parameter file configures the submap extraction module
/**:
  ros__parameters:
    localization:
      sub_map_extraction:
        # the module type (don't change this param)
        type: "sub_map_extraction"

        temporal_max_depth: 10    # vertices to search for scaled sigma
        temporal_min_depth: 5     # use at least a depth of 5
        search_spatially: true
        sigma_scale: 3.0
        angle_weight: 5.0