## This parameter file configures the multi-experience matcher module
/**:
  ros__parameters:
    localization:
      matcher:
        # the module type (don't change this param)
        type: "mel_matcher"

        descriptor_thresh_cpu: 0.115
        descriptor_thresh_gpu: 0.55
        target_match_count: 200
        min_match_count: 20
        matching_pixel_thresh: 200
        tight_matching_pixel_thresh: 50
        tight_matching_x_sigma: 0.1 # in [m]
        tight_matching_y_sigma: 0.1 # in [m]
        tight_matching_theta_sigma: 0.0 # in [rad] Note: In VTR2 was listed as 0.00349 but bug so always 0 in ModuleLoc
        min_response_ratio: 0.2
        time_allowance: 2000.0
        visualize: false
        min_track_length: 1
        max_depth_diff: 5.0
        max_landmark_depth: 200.0
        screen_matched_landmarks: true
        parallel_threads: 8
        match_on_gpu: false
        match_gpu_knn_match_num: 8