## This parameter file configures the MEL optimization module
/**:
  ros__parameters:
    localization:
      steam:
        # the module type (don't change this param)
        type: "keyframe_optimization"

        solver_type: "DoglegGaussNewton"
        loss_function: "DCS"

        iterations: 15
        verbose: false
        absoluteCostThreshold: 0.0
        absoluteCostChangeThreshold: .0001
        relativeCostChangeThreshold: .0001
        ratioThresholdShrink: 0.25
        ratioThresholdGrow: 0.75
        shrinkCoeff: 0.5
        growCoeff: 3.0
        maxShrinkSteps: 50
        backtrackMultiplier: 0.5
        maxBacktrackSteps: 10
        max_point_depth: 1000.0
        depth_prior_enable: true
        depth_prior_weight: 100000000.0

        pose_prior_enable: true

        use_migrated_points: true

        trajectory_smoothing: false
        velocity_prior: false

        disable_solver: false   # Set true to do everything but run optimise()
