## This parameter file configures the stereo RANSAC module
/**:
  ros__parameters:
    localization:
      ransac:
        # the module type (don't change this param)
        type: "stereo_ransac"

        enable: true
        flavor: Vanilla
        use_covariance: false
        iterations: 6000
        sigma: 3.5
        threshold: 10.0
        early_stop_ratio: 1.0
        early_stop_min_inliers: 400
        mask_depth: 1000.0
        mask_depth_inlier_count: 0
        min_inliers: 6

        visualize_ransac_inliers: true
        use_migrated_points: true
