## This parameter file configures the time-of-day recognition MEL module
/**:
  ros__parameters:
    localization:
      tod_recognition:
        # the module type to configure (don't change this param)
        type: "timeofday_recognition"

        # Whether to print out debug logs
        verbose: false

        # The weight to convert time-of-day difference to a distance
        # probably just leave this at 1.0, and adjust the rest
        time_of_day_weight: 1.0

        # The weight to convert total time difference to a distance
        # 1.0/24.0 means 1 day is worth 1 time-of-day hour
        # 1.0/(7.0*24.0) means 1 week is worth 1 time-of-day-hour
        total_time_weight: 0.00595 # 1.0/(7.0*24.0)

        # The number of experiences to recommend for localization
        num_desired_experiences: 8

        # Whether or not we make the recommendation and restrict the experiences
        in_the_loop: true
