/**:
  ros__parameters:

    ############ tactic configuration ############
    tactic:
      visualize: false
      localization_only_keyframe: true
      localization_skippable: false

    pipeline:
      localization:
        [
          "recall",
          "sub_map_extraction",
          "experience_triage",
          "migration",
          "matcher",
          "ransac",
          "steam",
        ]
    
    preprocessing:
      # conversion+extraction module
      extraction:
        type: conversion_extraction

        extractor:
          type: ASRL_GPU_SURF
          visualize_disparity: false
          use_learned: true

          learned:
            # we're providing the surf settings (don't change this param, use a different file)
            type: "LEARNED_FEATURE"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_16_crop_w16h15.pt"

            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_snow_16_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_snow_32_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_32_h15w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_extend_32_h15w16.pt"
            
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_snow_354_32_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_snow_391_16_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_extend_395_32_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_extend_479_32_h16w16.pt"
            # Lighting-change-extend-layer16
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_extend_585_16_h16w16.pt"
            # Lighting-change
            modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_165_32_h16w16.pt"
            # modelPath: "/home/asrl/libtorch_example/data/feature_detector_dark_62_16_h16w16.pt"

            stereoDisparityMinimum: 0.1
            stereoDisparityMaximum: 100.0

    odometry:
      ransac:
        type: stereo_ransac
        visualize_ransac_inliers: false

    localization:
      experience_triage:
        type: experience_triage
        only_privileged: true

      matcher:
        type: mel_matcher
        min_response_ratio: 0.0 #0.2
        descriptor_thresh_cpu: 0.7 #0.115, 0.2
        descriptor_thresh_gpu: 100.0 #0.55
        match_on_gpu: false
        visualize: false
        use_learned: true

      ransac:
        visualize_ransac_inliers: true

    ############ path tracker configuration ############
    path_tracker:
      # target_linear_speed: [0.6, 0.7, 0.8, 0.9]
      # target_linear_speed: [0.6, 0.75, 0.9, 1.1]
      target_linear_speed: [0.5, 0.6, 0.7, 0.8]
      # target_linear_speed: [0.55, 0.7, 0.8, 0.9]
      # target_linear_speed: [0.55, 0.7, 0.85, 1.0]

      weight_speed_input_mpc: 4.8       # 2. diff. btw. scheduled speed and commanded speed. 4 if driving slowly.
      enable_slow_start: false          # Taper desired speed profile at the start of the path

