/**:
  ros__parameters:
    bundle_adjustment:
      steam:
        # the module type to configure (don't change this param)
        type: "stereo_window_optimization"

        enable: true
        solver_type: "DoglegGaussNewton"
        loss_function: "DCS"
        iterations: 3
        verbose: false
        disable_solver: false # Set true to do everything but run optimise()

        absoluteCostThreshold: 0.0
        absoluteCostChangeThreshold: .01
        relativeCostChangeThreshold: .01
        ratioThresholdShrink: 0.25
        ratioThresholdGrow: 0.75
        shrinkCoeff: 0.5
        growCoeff: 3.0
        maxShrinkSteps: 50

        backtrackMultiplier: 0.5
        maxBacktrackSteps: 10

        depth_prior_enable: true
        depth_prior_weight: 100000000.0
        max_point_depth: 200.0

        trajectory_smoothing: true
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.01
        lin_acc_std_dev_z: 0.01
        ang_acc_std_dev_x: 0.1
        ang_acc_std_dev_y: 0.1
        ang_acc_std_dev_z: 1.0

        velocity_prior: true
        lin_vel_mean_x: 0.0
        lin_vel_mean_y: 0.0
        lin_vel_mean_z: 0.0
        ang_vel_mean_x: 0.0
        ang_vel_mean_y: 0.0
        ang_vel_mean_z: 0.0

        lin_vel_std_dev_x: 8.0
        lin_vel_std_dev_y: 0.5
        lin_vel_std_dev_z: 0.5
        ang_vel_std_dev_x: 0.5
        ang_vel_std_dev_y: 0.5
        ang_vel_std_dev_z: 1.0

        ## sample and save trajectory results to disk
        save_trajectory: false
