# This file contains params that are specific to this robot for this module. These params override the base params and are themselves overriden by the scenario params
/**:
  ros__parameters:
    odometry:
      steam:
        verbose: false
        trajectory_smoothing: true
        ## smoothing factor
        ## zero mean white noise on acceleration
        ## one-sigma standard deviation for linear acceleration (m/s/s)
        lin_acc_std_dev_x: 0.25 ## lifted from max acceleration in grizzly launch
        lin_acc_std_dev_y: 0.001 ## grizzly does not strafe very fast
        lin_acc_std_dev_z: 0.1 ## neither does it jump quickly, except for going over bumps

        ## one-sigma standard devitation for angular acceleration (rad/s/s0)
        ang_acc_std_dev_x: 0.001 # roll rate, should be low
        ang_acc_std_dev_y: 0.001 # pitch rate,
        ang_acc_std_dev_z: .003 # yaw rate, approx 2 deg

        velocity_prior: true
        lin_vel_mean_x: 0.0
        lin_vel_mean_y: 0.0
        lin_vel_mean_z: 0.0
        ang_vel_mean_x: 0.0
        ang_vel_mean_y: 0.0
        ang_vel_mean_z: 0.0

        ## standard deviation for velocity prior
        ## linear velocity m/s
        lin_vel_std_dev_x: 3.0 ## the grizzly is usually within +- 3.0 m/s
        lin_vel_std_dev_y: 0.02
        lin_vel_std_dev_z: 0.02

        ## angular velocity rad/s
        ang_vel_std_dev_x: 0.001
        ang_vel_std_dev_y: 0.001
        ang_vel_std_dev_z: 0.003

        ## sample and save trajectory results to disk
        save_trajectory: false
