# This file contains params that are specific to this robot for this module. These params override the base params and are themselves overriden by the scenario params
/**:
  ros__parameters:
    odometry:
      ransac:
        early_stop_ratio: 0.8
        early_stop_min_inliers: 150
