# This file contains params that are specific to this robot for this module. These params override the base params and are themselves overriden by the scenario params
/**:
  ros__parameters:
    odometry:
      vertex_test:  
        min_distance: .05
        min_creation_distance: 0.3
        max_creation_distance: 2.0
        rotation_threshold_min: 3.0
        rotation_threshold_max: 20.0
        match_threshold_min_count: 50
        match_threshold_fail_count: 15
