/**:
  ros__parameters:
    ############ system configuration ############

    ############ map projection configuration ############
    map_projection:
      origin_lat: 43.78215
      origin_lng: -79.46605
      origin_theta: -0.2 # positive == clockwise
      scale: 1.0

    ############ tactic configuration ############
    tactic:
      visualize: true
      default_loc_cov: [1.0, 0.5, 0.5, 0.25, 0.25, 0.5]
      merge_threshold: [5.0, 3.0, 0.2]
      chain:
        min_cusp_distance: 1.5
        angle_weight: 7.0
        search_depth: 20
        search_back_depth: 10
        distance_warning: 3.0

    ############ pipeline configuration ############
    pipeline:
      # pipeline parameters
      map_voxel_size: 0.3

    preprocessing:
      preprocessing:
        num_channels: 128
        vertical_angle_res: 0.00192
        polar_r_scale: 6.0
        r_scale: 2.0
        h_scale: 1.0
        num_sample1: 100000
        min_norm_score1: 0.95

        num_sample2: 20000
        min_norm_score2: 0.2 # 0.2 is where 5/12 * pi
        ideal_normal_estimate_dist: 10.0

        cluster_num_sample: 10000

        frame_voxel_size: 0.2

    odometry:
      recall:
        type: "lidar.map_recall"
        map_voxel_size: 0.3
        visualize: false

      icp:
        trajectory_smoothing: true
        use_constant_acc: false
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.1
        lin_acc_std_dev_z: 0.1
        ang_acc_std_dev_x: 0.1
        ang_acc_std_dev_y: 0.1
        ang_acc_std_dev_z: 1.0

        # ICP parameters
        num_threads: 12
        initial_max_iter: 10
        initial_num_samples: 5000
        initial_max_pairing_dist: 5.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 5000
        refined_max_pairing_dist: 2.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.3

      mapping:
        # dynamic objects removal
        horizontal_resolution: 0.01
        vertical_resolution: 0.01
        min_num_observations: 1
        max_num_observations: 20

      keyframe_test:
        type: "lidar.keyframe_test"

        min_translation: 5.0
        min_rotation: 15.0
        max_translation: 10.0
        max_rotation: 45.0

        min_matched_points_ratio: 0.55

        max_num_frames: 300

    localization:
      recall:
        type: "lidar.windowed_map_recall"
        map_voxel_size: 0.3
        depth: 4
        num_additional_exps: 3
        visualize: true

      icp:
        type: "lidar.localization_icp"

        use_pose_prior: true

        # ICP parameters
        num_threads: 12
        first_num_steps: 10
        initial_max_iter: 50
        initial_num_samples: 5000
        initial_max_pairing_dist: 10.0
        initial_max_planar_dist: 0.3
        refined_max_iter: 50
        refined_num_samples: 5000
        refined_max_pairing_dist: 2.0
        refined_max_planar_dist: 0.1

        min_matched_ratio: 0.3
