/**:
  ros__parameters:
    ############ system configuration ############

    ############ tactic configuration ############
    map_projection:
      origin_lat: 40.53748384
      origin_lng: -75.54330492
      origin_theta: 1.16 # positive == clockwise
      scale: 1.0

    ############ pipeline configuration ############
    pipeline:
      # pipeline parameters
      map_voxel_size: 0.1

    preprocessing:
      preprocessing:
        num_channels: 128
        vertical_angle_res: 0.013 # 0.013055612514918213  (95 degree fov)
        polar_r_scale: 2.0
        r_scale: 2.0
        h_scale: 3.208 # 2 * pi / (15 * 5 * 2) approx 0.041887902047863905
        num_sample1: 90000
        num_sample2: 10000
        min_norm_score1: 0.0
        min_norm_score2: 0.01
        frame_voxel_size: 0.1

    odometry:
      recall:
        map_voxel_size: 0.1

      icp:
        trajectory_smoothing: true
        use_constant_acc: false
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.1
        lin_acc_std_dev_z: 0.1
        ang_acc_std_dev_x: 0.1
        ang_acc_std_dev_y: 0.1
        ang_acc_std_dev_z: 1.0

        max_pairing_dist: 1.0
        max_planar_dist: 0.3

        min_matched_ratio: 0.0

      mapping:
        map_voxel_size: 0.1
        # dynamic objects removal
        horizontal_resolution: 0.050 # 0.041887902047863905
        vertical_resolution: 0.015 # 0.012953615542145415

      keyframe_test:
        min_translation: 0.5
        min_rotation: 10.0
        min_matched_points_ratio: 0.0
