/**:
  ros__parameters:
    odometry:
      matcher:
        # the module type to configure (don't change this param)
        type: "asrl_stereo_matcher"
        check_laplacian_bit: true
        check_octave: true
        check_response: false
        min_response_ratio: 0.2
        matching_pixel_thresh: 100.0
        tight_matching_pixel_thresh: 50.0

        # !!! The covariance is currently set to identity * dt*dt,
        # So the sigma will be dt, where dt is the time difference
        # between the last keyframe and the live frame.
        # This is ugly, but it is mirroring the mel matcher for
        # simplicity, since we are just trying to get things working.
        # in the case that we're not extrapolating and using identity,
        # the covariance is multiplied by 4 (dt is doubled).
        # This is not currently configurable.
        # e.g. 0.4 is 400 ms while extrapolating, and 200 ms with identity
        tight_matching_x_sigma: 0.4 # in s
        tight_matching_y_sigma: 0.4 # in s
        tight_matching_theta_sigma: 0.4 # in s

        use_pixel_variance: true
        prediction_method: se3
        max_point_depth: 1000
        descriptor_thresh: 0.1
        parallel_threads: 8
        visualize_feature_matches: false
        min_matches: 0
