/**:
  ros__parameters:
    odometry:
      steam:
        # the module type to configure (don't change this param)
        type: "keyframe_optimization"

        solver_type: "DoglegGaussNewton"
        loss_function: "DCS"

        iterations: 2
        verbose: false
        absoluteCostThreshold: 0.0
        absoluteCostChangeThreshold: .0001
        relativeCostChangeThreshold: .0001
        ratioThresholdShrink: 0.25
        ratioThresholdGrow: 0.75
        shrinkCoeff: 0.5
        growCoeff: 3.0
        maxShrinkSteps: 50
        backtrackMultiplier: 0.5
        maxBacktrackSteps: 10
        max_point_depth: 200.0
        depth_prior_enable: true
        depth_prior_weight: 100000000.0
        pose_prior_enable: false

        use_migrated_points: false
        disable_solver: false # Set true to do everything but run optimise()

        # Smoothing based on vehicle dynamics,
        # tune these for your robot in your robot-specific config
        # E.g. a nonholonomic ground vehicle on rugged terrain:
        trajectory_smoothing: true
        lin_acc_std_dev_x: 1.0
        lin_acc_std_dev_y: 0.01
        lin_acc_std_dev_z: 0.01
        ang_acc_std_dev_x: 0.1
        ang_acc_std_dev_y: 0.1
        ang_acc_std_dev_z: 1.0

        # Mean for the velocity prior (0 mean is probably what you want)
        velocity_prior: true
        lin_vel_mean_x: 0.0
        lin_vel_mean_y: 0.0
        lin_vel_mean_z: 0.0
        ang_vel_mean_x: 0.0
        ang_vel_mean_y: 0.0
        ang_vel_mean_z: 0.0

        # Covariance for the velocity prior (how close is typical motion to 0 mean)
        lin_vel_std_dev_x: 8.0
        lin_vel_std_dev_y: 0.5
        lin_vel_std_dev_z: 0.5
        ang_vel_std_dev_x: 0.5
        ang_vel_std_dev_y: 0.5
        ang_vel_std_dev_z: 1.0

        ## sample and save trajectory results to disk
        save_trajectory: false
