/**:
  ros__parameters:
    odometry:
      ransac:
        # the module type to configure (don't change this param)
        type: "stereo_ransac"
        rig: "front_xb3"
        channel: "grayscale"
        enable: true
        flavor: Vanilla
        use_covariance: false
        iterations: 2000
        sigma: 3.5
        threshold: 5.0
        early_stop_ratio: 1.0
        early_stop_min_inliers: 200
        mask_depth: 200.0
        mask_depth_inlier_count: 0
        min_inliers: 15

        use_migrated_points: false
        visualize_ransac_inliers: true
