/**:
  ros__parameters:
    odometry:
      vertex_test:
        # the module type to configure (don't change this param)
        type: "simple_vertex_creation_test"

        min_distance: .05
        min_creation_distance: .2
        max_creation_distance: 1.0
        rotation_threshold_min: 2.0
        rotation_threshold_max: 20.0
        match_threshold_min_count: 100
        match_threshold_fail_count: 15
